### PR TITLE
Run formatter on *.cc & *.h

### PR DESCRIPTION
**Pull request by anton-buyskikh**
I've ran the first code style formatter I came across. Thus all cpp files look the same.
If you prefer to use another style, just let me know which one.

The code is not changed by this PR, only its style.

### CODE REVIEW

**Comment by Shovan-Physics** [comment]
I'm not sure I understand what you mean.. so this is changing the style of the files without changing the content? How would the cpp files look different? What would you have done?

**Comment by anton-buyskikh** [comment]
@Shovan-Physics click on **Files changed** above and you will see everything.
The code is not changed, only the style's been updated, i.e. spacing.
Thus the executable code is identical.

I used an automatic tool from VSCode, thus all files follow the same style pattern now.

**Comment by Shovan-Physics** [comment]
OK, it looks alright to me, and I don't know what other styles are there, so I'll just approve it!

**Review by Shovan-Physics — APPROVED** [review]

**Comment by anton-buyskikh** [comment]
Ah sorry, I've forgot that we don't have any tests here. Would you mind at least checkout this version and recompile this code? At lease we should see that there are no odd errors.

**Comment by Shovan-Physics** [comment]
Sure, I will

**Comment by Shovan-Physics** [comment]
@anton-buyskikh Hi Anton, I ran this version for the sample parameters. It worked fine.

**Comment by Shovan-Physics** [comment]
@anton-buyskikh Can we merge this pull request while retaining subsequent changes to the main branch (e.g. license, standard makefile etc)?

**Comment by Shovan-Physics** [comment]
@anton-buyskikh I also made the following changes to the main branch: 
(1) Modified the README as we discussed last time 
(2) Added the new file `cDMRG_inputIDgen.nb` for storing/finding input IDs
(3) Modified the file `cDMRG_input_documentation.nb`

**Comment by Shovan-Physics** [comment]
@anton-buyskikh I guess the easiest option is to rerun the formatter on the `.cc` and `.h` files in the main branch and directly change those.

**Pull request merged**
